services:
  router:
    image: ubuntu
    container_name: router
    privileged: true
    networks:
      internal:
        ipv4_address: 10.0.0.2
      external:
        ipv4_address: 10.0.1.2
    command: >
      sh -c "
        echo 1 > /proc/sys/net/ipv4/ip_forward &&
        apt update &&
        apt install -y iptables iputils-ping &&
        iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
        tail -f /dev/null
      "

  target:
    image: ubuntu
    container_name: target
    networks:
      internal:
        ipv4_address: 10.0.0.4
    command: >
      sh -c "
        apt update &&
        apt install -y iputils-ping &&
        tail -f /dev/null
      "

  attacker:
    image: ubuntu
    container_name: attacker
    networks:
      internal:
        ipv4_address: 10.0.0.6
    volumes:
      - ./mitm.py:/root/mitm.py
      - ./requirements.txt:/root/requirements.txt
    command: >
      sh -c "
        apt update &&
        apt install -y iputils-ping python3 python3-pip python3-venv &&
        echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf &&
        sysctl -p &&
        tail -f /dev/null 
      "


networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

  external:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
