version: '3.8'
services:
  router:
    image: ubuntu
    container_name: router
    privileged: true
    hostname: router
    networks:
      internal:
        ipv4_address: 10.0.0.2
      external:
        ipv4_address: 10.0.1.2
    command: >
      sh -c "
        echo 1 > /proc/sys/net/ipv4/ip_forward &&
        apt update &&
        apt install -y iptables iputils-ping &&
        iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE &&
        tail -f /dev/null
      "

  target:
    image: ubuntu
    container_name: target
    privileged: true
    hostname: target
    networks:
      internal:
        ipv4_address: 10.0.0.4
    command: >
      sh -c "
        apt update &&
        apt install -y iputils-ping iproute2 net-tools curl lynx && 
        ip route del default &&
        ip route add default via 10.0.0.2
        tail -f /dev/null
      "

  webtarget:
    image: ubuntu
    container_name: webtarget
    privileged: true
    hostname: webtarget
    networks:
      internal:
        ipv4_address: 10.0.0.6
    command: >
      sh -c "
      apt update &&
      apt install -y iputils-ping iproute2 apache2 &&
      ip route del default &&
      ip route add default via 10.0.0.2 &&
      service apache2 start &&
      tail -f /dev/null
      "
  attacker:
    image: ubuntu
    container_name: attacker
    privileged: true
    hostname: attacker
    networks:
      internal:
        ipv4_address: 10.0.0.10
    volumes:
      - ./:/root/mitm
    command: >
      sh -c "
        apt update &&
        dpkg --configure -a &&
        apt install -y iputils-ping python3 python3-pip python3-venv tcpdump sudo &&
        pip3 install -r /root/mitm/src/requirements.txt --break-system-packages &&
        sysctl -p &&
        tail -f /dev/null 
      "

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

  external:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.1.0/24
